Platform =
case os:type() of
    {unix, linux} ->
        linux;
    _ ->
        false
end.
Fun =
    fun
        ({deps, Deps}) when Platform =/= linux ->
            {deps, lists:keydelete(procket, 1, Deps)};
        ({overrides, Overrides}) when Platform =/= linux ->
            {overrides, lists:keydelete(gen_socket, 2, Overrides)};
        (Term) ->
            Term
    end.

lists:map(Fun, CONFIG).
