Platform =
case os:type() of
    {unix, linux} ->
        linux;
    _ ->
        false
end.
Fun =
    fun
        ({deps, Deps}) when Platform =/= linux ->
            {deps, lists:keydelete(procket, 1, Deps)};
        ({overrides, Overrides0}) when Platform =/= linux ->
            Override = {override, procket, [{pre_hooks, []}, {post_hooks, []}]},
            {overrides, [Override|Overrides0]};
        (Term) ->
            Term
    end.

lists:map(Fun, CONFIG).
